TARGET = cirbuf

SRC  = cirbuf_add_buf_head.c cirbuf_add_head.c cirbuf.c 
SRC += cirbuf_del_buf_tail.c cirbuf_del_tail.c cirbuf_get_buf_tail.c
SRC += cirbuf_get_tail.c cirbuf_add_buf_tail.c cirbuf_add_tail.c 
SRC += cirbuf_del_buf_head.c cirbuf_del_head.c cirbuf_get_buf_head.c 
SRC += cirbuf_get_head.c cirbuf_align.c


###########################################

include $(AVERSIVE_DIR)/mk/aversive_module.mk
