
# Module names (not filenames)
OBJS = adns9500_spi adns9500_controlunit adns9500_latch_nbits adns9500_wishbone_interface \
			 adns9500_mode_mux top_adns9500
BENCHS =
SRC_EXTRA = 

include ../Makefile.inc

