
# Module names (not filenames)
OBJS = adns9500_spi adns9500_controlunit adns9500_latch_nbits adns9500_wishbone_interface \
			 adns9500_mode_mux top_adns9500
BENCHS = t_top_adns9500
SRC_EXTRA = bench/p_wishbone_testbench.vhd

include ../Makefile.inc

