DossierTech2010Robotter.pdf : *.tex *.sty
	pdflatex DossierTech2010Robotter.tex && pdflatex DossierTech2010Robotter.tex
	rm -vf *.toc *.out *.aux *.log
	chmod 664 *.pdf
	
clean :
	rm -vf *.toc *.out *.aux *.log *.pdf

