
# Module names (not filenames)
OBJS = adns6010_spi adns6010_controlunit adns6010_latch_nbits adns6010_wishbone_interface \
			 compass_reader compass_wbs compass_top
BENCHS = t_adns6010_spi t_adns6010_controlunit t_adns6010_latch_nbits \
				 t_compass_reader

include ../Makefile.inc

