
# Module names (not filenames)
OBJS = stratcomm_i2cslave stratcomm_control_unit stratcomm_wishbone 
BENCHS = t_stratcomm_i2cslave t_stratcomm_control_unit
SRC_EXTRA = hdl/std_logic_1164_ram.vhd

include ../Makefile.inc

