/*  
 *  Copyright Droids Corporation, Microb Technology, Eirbot (2007)
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *  Revision :  $
 *
 */

/* WARNING : this file is automatically generated by scripts.
 * You should not edit it. If you find something wrong in it,
 * write to zer0@droids-corp.org */

#ifndef _AVERSIVE_PARTS_H_
#define _AVERSIVE_PARTS_H_

#if defined (__AVR_AT90S1200__)
#include <aversive/parts/AT90S1200.h>
#elif defined (__AVR_AT90S2313__)
#include <aversive/parts/AT90S2313.h>
#elif defined (__AVR_AT90S2323__)
#include <aversive/parts/AT90S2323.h>
#elif defined (__AVR_AT90S2343__)
#include <aversive/parts/AT90S2343.h>
#elif defined (__AVR_AT90S4433__)
#include <aversive/parts/AT90S4433.h>
#elif defined (__AVR_AT90S8515__)
#include <aversive/parts/AT90S8515.h>
#elif defined (__AVR_AT90S8535__)
#include <aversive/parts/AT90S8535.h>
#elif defined (__AVR_ATmega103__)
#include <aversive/parts/ATmega103.h>
#elif defined (__AVR_ATmega1281__)
#include <aversive/parts/ATmega1281.h>
#elif defined (__AVR_ATmega128__)
#include <aversive/parts/ATmega128.h>
#elif defined (__AVR_ATmega161__)
#include <aversive/parts/ATmega161.h>
#elif defined (__AVR_ATmega162__)
#include <aversive/parts/ATmega162.h>
#elif defined (__AVR_ATmega163__)
#include <aversive/parts/ATmega163.h>
#elif defined (__AVR_ATmega165__)
#include <aversive/parts/ATmega165.h>
#elif defined (__AVR_ATmega168__)
#include <aversive/parts/ATmega168.h>
#elif defined (__AVR_ATmega169__)
#include <aversive/parts/ATmega169.h>
#elif defined (__AVR_ATmega16__)
#include <aversive/parts/ATmega16.h>
#elif defined (__AVR_ATmega2561__)
#include <aversive/parts/ATmega2561.h>
#elif defined (__AVR_ATmega323__)
#include <aversive/parts/ATmega323.h>
#elif defined (__AVR_ATmega3250__)
#include <aversive/parts/ATmega3250.h>
#elif defined (__AVR_ATmega325__)
#include <aversive/parts/ATmega325.h>
#elif defined (__AVR_ATmega3290__)
#include <aversive/parts/ATmega3290.h>
#elif defined (__AVR_ATmega329__)
#include <aversive/parts/ATmega329.h>
#elif defined (__AVR_ATmega32__)
#include <aversive/parts/ATmega32.h>
#elif defined (__AVR_ATmega406__)
#include <aversive/parts/ATmega406.h>
#elif defined (__AVR_ATmega640__)
#include <aversive/parts/ATmega640.h>
#elif defined (__AVR_ATmega644__)
#include <aversive/parts/ATmega644.h>
#elif defined (__AVR_ATmega645__)
#include <aversive/parts/ATmega645.h>
#elif defined (__AVR_ATmega649__)
#include <aversive/parts/ATmega649.h>
#elif defined (__AVR_ATmega64__)
#include <aversive/parts/ATmega64.h>
#elif defined (__AVR_ATmega8515__)
#include <aversive/parts/ATmega8515.h>
#elif defined (__AVR_ATmega8535__)
#include <aversive/parts/ATmega8535.h>
#elif defined (__AVR_ATmega88__)
#include <aversive/parts/ATmega88.h>
#elif defined (__AVR_ATmega8__)
#include <aversive/parts/ATmega8.h>
#elif defined (__AVR_ATtiny11__)
#include <aversive/parts/ATtiny11.h>
#elif defined (__AVR_ATtiny12__)
#include <aversive/parts/ATtiny12.h>
#elif defined (__AVR_ATtiny13__)
#include <aversive/parts/ATtiny13.h>
#elif defined (__AVR_ATtiny15__)
#include <aversive/parts/ATtiny15.h>
#elif defined (__AVR_ATtiny2313__)
#include <aversive/parts/ATtiny2313.h>
#elif defined (__AVR_ATtiny24__)
#include <aversive/parts/ATtiny24.h>
#elif defined (__AVR_ATtiny26__)
#include <aversive/parts/ATtiny26.h>
#elif defined (__AVR_ATtiny28__)
#include <aversive/parts/ATtiny28.h>
#elif defined (__AVR_ATtiny44__)
#include <aversive/parts/ATtiny44.h>
#elif defined (__AVR_ATtiny45__)
#include <aversive/parts/ATtiny45.h>
#elif defined (__AVR_ATtiny84__)
#include <aversive/parts/ATtiny84.h>
#elif defined (__AVR_ATtiny861__)
#include <aversive/parts/ATtiny861.h>
#else
#error "This arch is not implemented yet"
#endif

#endif /* _AVERSIVE_PARTS_H_ */
