TARGET = main

SRC = $(TARGET).c cs.c motor_cs.c robot_cs.c htrajectory.c logging.c fpga.c compass.c acfilter.c hposition_manager.c hrobot_manager.c reset.c motor_encoders.c avoidance.c cord.c

include ../../mk/project.mk
