#ifndef R3D2_CONFIG_H
#define R3D2_CONFIG_H

#define DEFAULT_MOTOR_SPEED 2200
#define DEFAULT_DETECTION_THRESHOLD 5
#define DEFAULT_MOTOR_WATCHDOG_TIMEOUT 5
#define DEFAULT_ANGLE_OFFSET (80.0*M_PI/180)
#define DEFAULT_DISTANCE_COEF 2.0

#endif
