
# Module names (not filenames)
OBJS = multiplier33 multiplier63 multiplier93 posman posman_control dual_ram posman_wishbone_interface
BENCHS = t_multipliers t_posman
SRC_EXTRA = bench/txt_util.vhd bench/p_wishbone_testbench.vhd

include ../Makefile.inc

