#!/bin/bash

(gnuplot <<EOF
set terminal postscript eps color "Times-Roman" 16
set output 'in-out.eps'
set multiplot
set yrange [-6000:11000]
plot "data" using 1:2 with lines, "data" using 1:3 with lines
EOF
) &

(gnuplot <<EOF
set terminal postscript eps color "Times-Roman" 16
set output 'speed.eps'
set multiplot
set yrange [-110:110]
plot "data" using 1:4 with lines
EOF
)&

